
#datasources:
#  default:
#    url: jdbc:mysql://localhost:3306/db
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ''
consul:
  client:
    defaultZone: ${CONSUL_HOST:containers.quos.io}:${CONSUL_PORT:4500}
    registration:
      enabled: true
#kafka.bootstrap.servers: kafka:9092
#dataSource:
#  url: jdbc:mysql://localhost:3306/db
#  driverClassName: com.mysql.cj.jdbc.Driver
#  username: root
#  password: ''
#  pooled: true
#  jmxExport: true
#hibernate:
#  hbm2ddl:
#    auto: update
#  cache:
#    queries: false
#    use_second_level_cache: false
#    use_query_cache: false
netty:
  default:
    allocator:
      max-order: 3
