#micronaut:
#  server:
#    host: ${CS_AIRPORT_SERVICE_HOST}
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  logSql: false
  dbCreate: update
  url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/cs_airport?serverTimezone=EST5EDT&allowPublicKeyRetrieval=true&useSSL=false
  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

consul:
  client:
    defaultZone: ${CONSUL_HOST:containers.quos.io}:${CONSUL_PORT:4500}
    registration:
      enabled: true

kafka.bootstrap.servers: ${ZKLESS_KAFKA_BOOTSTRAP_SERVICE_HOST:zkless-kafka-bootstrap}:${ZKLESS_KAFKA_BOOTSTRAP_SERVICE_PORT:9092}
netty:
  default:
    allocator:
      max-order: 3
